### ISSUE TITLE
Support Go 1.5 and 1.6?

### ISSUE THREAD

**Issue by hkdnet** [ugorji/go#306]
I found the current `master` branch (247404d1fab0e48325e72fe995555979251857cf) cannot be built with either 1.5 or 1.6.
It has been caused since 31b118dd0628c36594c1707e7dcbbd411c705c88, because `func mapRange` definition is missing for versions less than 1.7.

```
$ go get github.com/ugorji/go/codec
# github.com/ugorji/go/codec
../../ugorji/go/codec/encode.go:587: undefined: mapRange
```

Our library depends on this library and it is tested on versions more than or equal to 1.5 (https://github.com/treasure-data/td-client-go/issues/27).
If `github.com/ugorji/go/codec` does not support versions less than 1.7, we plan to simply remove test targets.
So, I'd like to know whether Go 1.5 and 1.6 are supported or not.

**Comment by ugorji** [comment]
It should be. But I haven't run tests on that Target in a while, because the test suite feature I use for running suite of treats isn't supported there. I can support it in the code though. 

Will fix.

**Comment by hkdnet** [comment]
OK, thanks 😸
